FROM golang:1.24-alpine

WORKDIR /app

RUN apk add --no-cache git && \
    go install github.com/air-verse/air@v1.62.0 && \
    apk del git

COPY go.mod go.sum ./
RUN go mod download

COPY . .

EXPOSE 8080

CMD ["air"]
